name: Build Windows Application
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Compiler
      run: pip install pyinstaller

    - name: Create Executable File
      run: pyinstaller --noconsole --onefile converter.py

    - name: Save Finished File
      uses: actions/upload-artifact@v4
      with:
        name: Shopify-Wheel-Converter-Windows
        path: dist/converter.exe
